services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goku
    ports:
      - "5448:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
