// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"
)

const saveDocument = `-- name: SaveDocument :one
INSERT INTO documents (
    name,
    data_format,
    data
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, data_format, data, created_at, updated_at
`

type SaveDocumentParams struct {
	Name       string `json:"name"`
	DataFormat string `json:"data_format"`
	Data       []byte `json:"data"`
}

func (q *Queries) SaveDocument(ctx context.Context, arg SaveDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, saveDocument, arg.Name, arg.DataFormat, arg.Data)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DataFormat,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
